apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 1
  template:
    metadata:
      name: "goserver"
      labels:
        app: "goserver"
    spec:
      containers:
        - name: goserver
          image: jamesfrj/fc-go-server:v6.2

          readinessProbe:
            httpGet: 
              path: /health
              port: 8080
            periodSeconds: 3
            failureThreshold: 1
            initialDelaySeconds: 10  

          # livenessProbe:
          #   httpGet: 
          #     path: /health
          #     port: 8080
          #   periodSeconds: 5
          #   failureThreshold: 3
          #   timeoutSeconds: 1
          #   successThreshold: 1

          envFrom:
            - configMapRef: 
                name: goserver-env
            - secretRef:
                name: goserver-secret

          volumeMounts:
            - mountPath: "/go/myfamily"
              name: config

      volumes:
        - name: config
          configMap:
            name: configmap-family
            items:
            - key: members
              path: "family.txt"